wheel:
  mass: 1.0         # Wheel mass in Kilograms       
  radius: 0.18      # Wheel radius in meters 
  length: 0.05      # Wheel length in meters, considering it as a cylinder 
  mesh: ''          # Name of the mesh files. Leave it empty ('') to have a red wheel. 
  x_offset: 0.16    # Offset distance on the x-axis in meters.
  y_offset: 0.002  # Offset distance on the y-axis in meters.
  z_offset: -0.003   # Offset distance on the z-axis in meters.